MODES = {
 "normal":
     {
	"note" : [
            "left",
            "down",
            "right",
            "up",
            "start",
            "right_hat",
            "left_hat",
            "select",
            "square",
            "ex",
            "circle",
            "triangle",
            "r1",
            "l1",
            "r2",
            "l2",
            ],
        "cc" : [
            "left_analog_horiz",
            "left_analog_vert",
            "right_analog_horiz",
            "right_analog_vert",
            "accX",
            "accY",
            "accZ",
            ],
        "pitch": [
            ],
        },
 "pitch":
     {
	"note" : [
            "left",
            "down",
            "right",
            "up",
            "start",
            "right_hat",
            "left_hat",
            "select",
            "square",
            "ex",
            "circle",
            "triangle",
            "r1",
            "l1",
            "r2",
            "l2",
            ],
        "cc" : [
            "left_analog_horiz",
            "left_analog_vert",
            "accX",
            "accY",
            "accZ",
            ],
        "pitch": [
            "right_analog_horiz",
            "right_analog_vert",
            ],
        },
 "pitch2":
     {
	"note" : [
            "left",
            "down",
            "right",
            "up",
            "start",
            "right_hat",
            "left_hat",
            "select",
            "square",
            "ex",
            "circle",
            "triangle",
            ],
        "cc" : [
            "l1",
            "l2",
            "left_analog_horiz",
            "left_analog_vert",
            "right_analog_horiz",
            "right_analog_vert",
            "accX",
            "accY",
            "accZ",
            ],
        "pitch_two_side": [
            "r1",
            "r2",
            ],
        },
 }
